### PR TITLE
Fixes for multi-function CleanRepo run

### LINKED ISSUE #147: CleanRepo: Optimize for multiple options to run at once
Also, add new options for different start directories for articles, media, snippets, and include files.

---
[Associated WorkItem - 69088](https://dev.azure.com/msft-skilling/Content/_workitems/edit/69088)

### PR DESCRIPTION
**Pull request by gewarren**
Fixes #147 

- added new function-specific start directory options
- optimized info retrieval so it only happens once per run where possible

### CODE REVIEW

File: cleanrepo/CleanRepo/Options.cs [hunk 1]
```diff
@@ -2,26 +2,32 @@
 
 namespace CleanRepo;
 
-// Define a class to receive parsed values
+// Define a class to receive parsed values.
 class Options
 {
-    [Option("start-directory", HelpText = "Top-level directory in which to perform clean up (for example, find orphaned markdown files).")]
-    public string InputDirectory { get; set; }
+    [Option("docfx-directory", HelpText = "Directory that contains the docfx.json file of interest.")]
```
Comment (IEvangelist) [inline cleanrepo/CleanRepo/Options.cs:8]: All of these option name updates will have to be changed in the _action.yml_ as well. And if you want to change the mapping in what the GitHub Action accepts as input, you'd have to update the consuming workflows too.

**Review by IEvangelist — APPROVED** [review]
